version: '3'
services:
  web:
    build: .
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    restart: on-failure
    depends_on:
      - db
    command: npm start
    networks:
      - gmapnet
  db:
    image: "postgres:11"
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - /workspace/gmapper/db/initdb:/docker-entrypoint-initdb.d
    networks:
      - gmapnet  
networks:
  gmapnet:       