version: '3'
services:
  web:
    build: .
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    restart: on-failure
    depends_on:
      - db
    command: npm start
    networks:
      - gmapnet
  db:
    build: ./db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - gmapnet  
networks:
  gmapnet:       